### ISSUE TITLE
Cashback operator

### ISSUE THREAD

**Issue by reinhart1010** [RioChndr/jaksel-language#17]
Halo, sebagai pembuat [bahasa pemrograman yang berasal dari ~~merek~~ brand kopi decacorn](https://t.co/Pqm8O4J17e) gw literally mau include operator "cashback", kira-kira contohnya begini:

```
kalo bayar pakai gopay
  harga dicashback 40% maks 4000
perhaps bayar pakai shopeepay
  harga dicashback 10% maks 6000 kalo minimum harga 10000
udahan
```

**Comment by RioChndr** [comment]
Gw rasa ini gk related sama lingkungan jaksel language.
