### ISSUE TITLE
Standard library untuk perpajakan

### ISSUE THREAD

**Issue by reinhart1010** [RioChndr/jaksel-language#18]
Sebagai warga negara yang baik (™) we literally have to bayar pajak despite rada-rada ngeselin gitu...

Awalnya gw mau bikin `PPN`, `PB1`, && i++ jadi kek konstan gitu, for example konstan `_WIN32` and `__linux__` yang ada di C gitu...

Tapi, tapi kan... ngitung pajak kek PPh kan ribet, perlu liat paycheck gw berapa banyak lagi. Gw mau hal-hal sepele kek gini jadi gampang. Segampang klik "bayar" dan scan QR gitu...

Maybe kita perlu bikin standard library with functions yang ngevibes sama pajak gitu?

**Comment by RioChndr** [comment]
Kayanya gk related sama bahasa ini.

**Comment by yus-ham** [comment]
ini sih dibikin library atau extension tersendiri
