### ISSUE TITLE
Typescript code base?

### ISSUE THREAD

**Issue by flamrdevs** [RioChndr/jaksel-language#28]
Migrasi dari javascript ke typescript ?

**Comment by RioChndr** [comment]
Belum. kita fokuskan ke javascript dulu dan bikin cukup stabil dengan unit testing

**Comment by Sylent-Sys** [comment]
di projek fork saya udah di rubah ke Ts, mungkin belum sesuai standar Ts tapi sudah berhasil migrasi 100% maybe?
