### ISSUE TITLE
It will be good kalo ada syntax highlight?

### ISSUE THREAD

**Issue by xxidbr9** [RioChndr/jaksel-language#43]
🫥🫠

**Comment by cocatrip** [comment]
ada bang tapi baru untuk vim/neovim doang wkwkwkwk

**Comment by xxidbr9** [comment]
ooghey, dimana tuh? klo ada bisa bagi? bisa nanti bantu" buat porting ke vscode mhehe

**Comment by cocatrip** [comment]
@xxidbr9 ini bang [vim-jaksel](https://github.com/cocatrip/vim-jaksel), terima kasih banyak bang kalo bisa bantu porting ke vscode wkwkwkwk

**Comment by RioChndr** [comment]
setuju @cocatrip, nanti masukin aja ke readme link reponya
